[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "readTheDocs"
authors = [{name = "lena", email = "lenaphili@main.py"}]
dynamic = ["version", "description"]
